=== bensmith87/risk/player/src/main/resources/maps/map.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="map">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="point"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="point">
        <xs:complexType>
            <xs:attribute name="latitude" use="required" type="xs:decimal"/>
            <xs:attribute name="longitude" use="required" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bensmith87/risk/player/src/main/resources/maps/africa.xml
<?xml version="1.0"?>

<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="map.xsd">
    <point latitude="31.503629" longitude="31.816406"/>
    <point latitude="30.751278" longitude="29.091797"/>
    <point latitude="32.768800" longitude="22.324219"/>
    <point latitude="32.101190" longitude="19.951172"/>
    <point latitude="31.278551" longitude="19.951172"/>
    <point latitude="29.916852" longitude="18.984375"/>
    <point latitude="33.578015" longitude="10.810547"/>
    <point latitude="37.160317" longitude="10.722656"/>
    <point latitude="36.668419" longitude="3.251953"/>
    <point latitude="35.317366" longitude="-1.406250"/>
    <point latitude="34.161818" longitude="-6.679688"/>
    <point latitude="30.524413" longitude="-10.019531"/>
    <point latitude="26.824071" longitude="-13.798828"/>
    <point latitude="21.289374" longitude="-17.138672"/>
    <point latitude="16.804541" longitude="-16.083984"/>
    <point latitude="13.581921" longitude="-17.314453"/>
    <point latitude="8.667918" longitude="-13.447266"/>
    <point latitude="3.951941" longitude="-7.910156"/>
    <point latitude="4.915833" longitude="-1.669922"/>
    <point latitude="6.140555" longitude="3.867188"/>
    <point latitude="4.039618" longitude="5.800781"/>
    <point latitude="4.302591" longitude="8.349609"/>
    <point latitude="2.899153" longitude="10.019531"/>
    <point latitude="-1.054628" longitude="8.701172"/>
    <point latitude="-7.623887" longitude="13.007813"/>
    <point latitude="-11.264612" longitude="14.150391"/>
    <point latitude="-14.434680" longitude="12.392578"/>
    <point latitude="-17.560247" longitude="11.865234"/>
    <point latitude="-22.593726" longitude="14.677734"/>
    <point latitude="-26.509905" longitude="14.941406"/>
    <point latitude="-29.764377" longitude="17.138672"/>
    <point latitude="-33.211116" longitude="17.666016"/>
    <point latitude="-34.741612" longitude="19.248047"/>
    <point latitude="-34.234512" longitude="26.191406"/>
    <point latitude="-28.921631" longitude="31.816406"/>
    <point latitude="-25.403585" longitude="32.783203"/>
    <point latitude="-24.367114" longitude="35.595703"/>
    <point latitude="-19.890723" longitude="34.892578"/>
    <point latitude="-17.224758" longitude="38.671875"/>
    <point latitude="-15.284185" longitude="40.605469"/>
    <point latitude="-10.746969" longitude="40.341797"/>
    <point latitude="-5.615986" longitude="38.847656"/>
    <point latitude="-1.230374" longitude="41.748047"/>
    <point latitude="1.581830" longitude="44.560547"/>
    <point latitude="3.864255" longitude="47.812500"/>
    <point latitude="7.100893" longitude="49.394531"/>
    <point latitude="10.574222" longitude="51.328125"/>
    <point latitude="11.695273" longitude="51.152344"/>
    <point latitude="11.436955" longitude="48.691406"/>
    <point latitude="9.968851" longitude="43.066406"/>
    <point latitude="14.008696" longitude="41.308594"/>
    <point latitude="18.312811" longitude="37.968750"/>
    <point latitude="23.241346" longitude="35.156250"/>
    <point latitude="27.683528" longitude="33.574219"/>
</map>
